### ISSUE TITLE
Ajouter le contenu et les liens

### ISSUE THREAD

**Issue by Em-AK** [Em-AK/webeelab#3]
- [x] section Projets
- [x] section Contribuer
- [x] section Actus

**Comment by Em-AK** [comment]
J'ai écrit le contenu des sections [Contribuer et Actualités](https://em-ak.github.io/webeelab/#contribute). Il me reste à **lister tous les projets** actifs dans l' OpenBeeLab. D'après ce que j'ai trouvé sur le wiki il y a : 
- Beelance 4
- Beelance 5
- Embeedian
- Dataviz
- Serveurs (adminsys des outils gogs, mediawiki, ...)
- Bases de données (maintenance et évolutions)
- Hotspot
- PCB (je n'arrive pas trop à comprendre pour quoi faire)
- Ruchers
  - CAPC
  - Le bel ordinaire

Merci de me dire si j'en oublie ;)

**Comment by pgpGithub** [comment]
C'est beau! Très beau!!!
Le pcb c'est pour la partie elec de la balance, et c'est en gros progrès ces derniers jours grace à Damien,
Les ruchers y'a pas encore le bel ordinaire, c'est en projet,
Twitter et facebook sont quasi à l'abandon, on a aussi un diaspora mais c'est pareil...

**Comment by pgpGithub** [comment]
On pourrait mettre les concerts avec le son des abeilles aussi :)

**Comment by Em-AK** [comment]
Liste des projets à compléter https://framacalc.org/projets_openbeelab
